name: perl_test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        perl-version: ["5.24.0", "5.30.0", "5.38.0" ]
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
    name: Test Perl ${{ matrix.perl-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Perl ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: perl -V
      - run: perl test.pl
